baseURL = "https://revolution1000.github.io/personalweb/"
languageCode = "en-us"
title = "寻子雄"
theme = "ananke"

[taxonomies]
category = "categories"
tag = "tags"

[[menu.main]]
name = "Economy"
url = "/categories/economy/"
weight = 1

[[menu.main]]
name = "Natural Philosophy"
url = "/categories/philosophy/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3

[params]
author = "Xun Zixiong"
description = "Personal Website"

show_reading_time = true
show_post_nav_links = true

background_color_class = "bg-black"
